# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=100)),
            ],
        ),
    ]
